name: Quick Start Test
on:
    workflow_dispatch:

env: 
    GITHUB_USER: ${{github.repository_owner}}
    VERSION_NAME: "quick_start_${{github.run_number}}"

jobs:
    quick_start_test:
        runs-on: ubuntu-latest

        permissions:
            packages: write
        
        steps:
            - id: case
              uses: ASzc/change-string-case-action@v6
              with:
                string: ${{env.GITHUB_USER}}
            - uses: actions/checkout@v2
            - name: Docker Login
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                GITHUB_USER: ${{steps.case.outputs.lowercase}}
              run: |
                echo $GITHUB_USER
                docker login ghcr.io --username $GITHUB_USER --password $GITHUB_TOKEN
            - name: Docker Build
              env:
                GITHUB_USER: ${{steps.case.outputs.lowercase}}
              run: |
                echo $VERSION_NAME
                docker build . --file Dockerfile --tag ghcr.io/$GITHUB_USER/escape_speed:$VERSION_NAME
            - name: Docker Push
              env:
                  GITHUB_USER: ${{steps.case.outputs.lowercase}}
              run: |
                docker push ghcr.io/$GITHUB_USER/escape_speed:$VERSION_NAME
            - name: Docker Pull
              env:
                  GITHUB_USER: ${{steps.case.outputs.lowercase}}
              run: |
                docker rmi ghcr.io/$GITHUB_USER/escape_speed:$VERSION_NAME
                docker pull ghcr.io/$GITHUB_USER/escape_speed:$VERSION_NAME
            - name: Docker Remove
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: |
                curl -L \
                -X DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/users/$GITHUB_USER/packages/container/escape_speed/versions/$VERSION_NAME