name: SSH
on:
  workflow_dispatch: 

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
